version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/node_mongo
    docker:
      - image: circleci/node:18.14.0
      - image: mongo:4.2.0
    steps:
      - checkout
      - run:
          name: npm install
          command: 'npm install'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}      
      - run:
          name: test
          command: npm run test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml